package app.aaps.plugins.main.general.overview.glass

data class GlassLoopDashboardState(
    val isDarkTheme: Boolean = true,
    val isLoading: Boolean = false,
    val lastRunTime: String = "",
    val autoMode: Boolean = false,
    val requestedSMB: Double = 0.0,
    val glucose: Double = 0.0,
    val delta5m: Double = 0.0,
    val shortAvgDelta: Double = 0.0,
    val longAvgDelta: Double = 0.0,
    val iob: Double = 0.0,
    val targetBg: Double = 0.0,
    val predictedBg: Double = 0.0,
    val protection: String = "(OFF)",
    val maxIobProfile: Double = 0.0,
    val maxIobDynamic: Double = 0.0,
    val maxSmbProfile: Double = 0.0,
    val maxSmbDynamic: Double = 0.0,
    val isf: Double = 0.0,
    val stableBg: Int = 0,
    val reactFactorProfile: Double = 0.0,
    val reactFactorAdjusted: Double = 0.0,
    val hourlyFactorProfile: Double = 0.0,
    val hourlyFactorAdjusted: Double = 0.0,
    val tddStatus: String = "Basic Mode",
    val tirStatus: String = "Basic Mode",
    val tirLow1h: Double = 0.0,
    val tirLow24h: Double = 0.0,
    val lowGlucoseAlarms1h: Int = 0,
    val lowGlucoseAlarms24h: Int = 0,
    val tdd7DaysPerHour: Double = 0.0,
    val steps5m: Int = 0,
    val steps30m: Int = 0,
    val steps180m: Int = 0,
    val hourOfDay: Int = 0,
    val isWeekend: Boolean = false,
    val buildVersion: String = "",
    val aimiVersion: String = ""
)
